### ISSUE TITLE
E-social e Reinf

### ISSUE THREAD

**Issue by SilasAlvesJunior** [ACBrNet/ACBr.Net.Core#5]
Parabéns pelo projeto! Utiliza o acbr monitor plus. Sou desenvolvedor .net e gostaria de saber se no projeto abrange e-social e reinf?

**Comment by rftd** [comment]
Não abrange e no momento não temos planos para faze-lo.

**Comment by SilasAlvesJunior** [comment]
Vou concluir um projeto utilizando o acbr plus, mas tenho interesse em
colaborar a portabilidade.

Em qui, 6 de dez de 2018 19:36, Rafael Teno Dias <notifications@github.com
escreveu:
